version: '3'
services:
  shell:
    build:
      context: .
    ports:
      - "3000:3000"
  
  sales:
    build:
      context: .
    ports:
      - "3001:3000"

  users:
    build:
      context: .
    ports:
      - "3002:3000"
