version: '3'
services:
  shell:
    build:
      context: ./shell
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - sales
  
  sales:
    build:
      context: ./sales
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
