server {
  listen 80;

  location / {
    root /usr/share/nginx/html/shell;
    try_files $uri /index.html;
  }

  location /users {
    alias /usr/share/nginx/html/users;
    try_files $uri /index.html;
  }

  location /sales {
    alias /usr/share/nginx/html/sales;
    try_files $uri /index.html;
  }
}
